module SampleSongs
  LYRICS_WIKIA_EXAMPLE = ["I had a dream so big and loud",
                          "I jumped so high I touched the clouds",
                          "Wo-oah-oah-oah-oah-oh",
                          "(Wo-oah-oah-oah-oah-oh)",
                          "I stretched my hands out to the sky",
                          "We danced with monsters through the night",
                          "Wo-oah-oah-oah-oah-oh",
                          "(Wo-oah-oah-oah-oah-oh)",
                          "I'm never gonna look back, whoa",
                          "Never gonna give it up, no",
                          "Please don't wake me now",
                          "This is gonna be the best day of my life",
                          "My life-ah-ah-ah-ah-ah-ife",
                          "This is gonna be the best day of my life",
                          "My life-ah-ah-ah-ah-ah-ife",
                          "I howled at the moon with friends",
                          "And then the sun came crashing in",
                          "Wo-oah-oah-oah-oah-oh",
                          "(Wo-oah-oah-oah-oah-oh)",
                          "But all the possibilities",
                          "No limits just epiphanies",
                          "Wo-oah-oah-oah-oah-oh",
                          "(Wo-oah-oah-oah-oah-oh)",
                          "I'm never gonna look back, whoa",
                          "Never gonna give it up, no",
                          "Just don't wake me now",
                          "This is gonna be the best day of my life",
                          "My life-ah-ah-ah-ah-ah-ife",
                          "This is gonna be the best day of my life",
                          "My life-ah-ah-ah-ah-ah-ife",
                          "I hear it calling outside my window",
                          "I feel it in my soul (soul)",
                          "The stars were burning so bright",
                          "The sun was out 'til midnight",
                          "I say we lose control (control)",
                          "This is gonna be the best day of my life",
                          "My life-ah-ah-ah-ah-ah-ife",
                          "This is gonna be the best day of my life",
                          "My life-ah-ah-ah-ah-ah-ife",
                          "This is gonna be, this is gonna be, this is gotta be",
                          "The best day of my life",
                          "Everything is looking up, everybody up now",
                          "This is gonna be the best day of my life",
                          "My life-ah-ah-ah-ah-ah-ife"]

SONG_LYRICS_EXAMPLE = ["(Ooh, Ooh-Ooh, Ooh)",
                       "I had a dream so big and loud",
                       "I jumped so high I touched the clouds",
                       "Whoa-Oh-Oh-Oh-Oh-Oh-Oh (Whoa-Oh-Oh-Oh-Oh-Oh-Oh)",
                       "I stretched my hands out to the sky",
                       "We danced with monsters through the night",
                       "Whoa-Oh-Oh-Oh-Oh-Oh-Oh (Whoa-Oh-Oh-Oh-Oh-Oh-Oh)",
                       "I'm never gonna look back, Whoa-Oh",
                       "Never gonna give it up, No-Oh",
                       "Please don't wake me now",
                       "(Ooh, Ooh-Ooh, Ooh)",
                       "This is gonna be the best day of my life",
                       "(Ooh, Ooh-Ooh, Ooh) My li-i-i-i-i-i-ife",
                       "(Ooh, Ooh-Ooh, Ooh)",
                       "This is gonna be the best day of my life",
                       "(Ooh, Ooh-Ooh, Ooh) My li-i-i-i-i-i-ife",
                       "(Ooh, Ooh-Ooh, Ooh) Whoo",
                       "(Ooh, Ooh-Ooh, Ooh)",
                       "I howled at the moon with my friends",
                       "And then the sun came crashing in",
                       "Whoa-Oh-Oh-Oh-Oh-Oh-Oh (Whoa-Oh-Oh-Oh-Oh-Oh-Oh)",
                       "But all the possibilities",
                       "No limits just epiphanies",
                       "Whoa-Oh-Oh-Oh-Oh-Oh-Oh (Whoa-Oh-Oh-Oh-Oh-Oh-Oh)",
                       "I'm never gonna look back, Whoa-Oh",
                       "Never gonna give it up, No-Oh",
                       "Just don't wake me now",
                       "(Ooh, Ooh-Ooh, Ooh)",
                       "This is gonna be the best day of my life",
                       "(Ooh, Ooh-Ooh, Ooh) My li-i-i-i-i-i-ife",
                       "(Ooh, Ooh-Ooh, Ooh)",
                       "This is gonna be the best day of my life",
                       "(Ooh, Ooh-Ooh, Ooh) My li-i-i-i-i-i-ife",
                       "(Ooh, Ooh-Ooh, Ooh)",
                       "(Ooh, Ooh-Ooh, Ooh)",
                       "I hear it calling",
                       "Outside my window",
                       "I feel it in my soul (Soul)",
                       "The stars were burning so bright",
                       "The sun was out 'till midnight",
                       "I say we lose control (Control)",
                       "(Ooh, Ooh-Ooh, Ooh)",
                       "(Ooh, Ooh-Ooh, Ooh)",
                       "This is gonna be the best day of my life",
                       "(Ooh, Ooh-Ooh, Ooh) My li-i-i-i-i-i-ife",
                       "(Ooh, Ooh-Ooh, Ooh)",
                       "This is gonna be the best day of my life",
                       "(Ooh, Ooh-Ooh, Ooh) My li-i-i-i-i-i-ife",
                       "(Ooh, Ooh-Ooh, Ooh) This is gonna be, this is gonna be",
                       "This has gotta be, the best day of my life (Ooh, Ooh-Ooh, Ooh)",
                       "Everything is looking up, everybody up now",
                       "(Ooh, Ooh-Ooh, Ooh)",
                       "This is gonna be the best day of my liife",
                       "(Ooh, Ooh-Ooh, Ooh) My li-i-i-i-i-ife"]
end